### ISSUE TITLE
Implement test widget

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#1]
I have created the following files as an example test widget. This is how I think it should be based on the goal of making this modularized for widgets.

/resources/views/widgets/testwidget
/resources/views/widgets/testwidget/assets
/resources/views/widgets/testwidget/assets/js
/resources/views/widgets/testwidget/assets/js/testwidget.js
/resources/views/widgets/testwidget/assets/sass
/resources/views/widgets/testwidget/assets/sass/testwidget.sass

The goal here is to be able to include this widget with just one line of code in the template, such as in /resources/views/templates/content.blade.php

The idea here is that the template does not need to know anything about the widget, it just displays what the widget has in it, so there is no code for the widget css, javascript, etc needed in the template because the widget already includes this.

**Comment by barbosa89** [comment]
After doing many tests were found two options, Laravel hosts the assets in the public folder. Assets hosted on resources/assets are compiled into two files: app.js and app.css.

The options for make a widget with Laravel, these are follows:

**First option:**

Laravel Widget with package https://github.com/arrilot/laravel-widgets

Run in console:

`php artisan make:widget widgetName`

Estructure:

Configuration file:
/app/Widgets/WidgetName.php

Javascript
/public/js/widgets/widgetName.js


CSS
/public/css/widgets/widgetName.css

Views
/resources/views/widgets/widgetTemplate.blade.php

Compiling Assets
```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .scripts([
		'/public/js/widgets/widgetName.js',
	], 'public/js/all.js')
   .styles([
	    '/public/css/widgets/widgetName.css',
	], 'public/css/all.css');
```

Usage

In a template:

@widget('widgetName)

You can use the widget in any template, layout or partial.

In Laravel it is not possible to use assets located in the resources/views folder, only the assets in the public folder with vanilla javascript and in the resources/assets folder with SASS, LESS and EcmaScript 2015.

**Second option**

[VueJs](https://vuejs.org/) allows us to build components with HTML, Javascript and CSS in a single file.

![imagen](https://user-images.githubusercontent.com/9729573/28441326-d2d8e5c6-6d6f-11e7-8b3d-5a4efe2b9b54.png)

Usage:

In a template:
```
<ol>
  <!-- Create an instance of the todo-item component -->
  <component-name></component-name>
</ol>
```
More info: [VueJs Get Started](https://vuejs.org/v2/guide/)
The second option is for projects hosted in a VPS or Server.

**Comment by stacksavings** [comment]
@barbosa89 Omar, this is excellent, I think the option of https://github.com/arrilot/laravel-widgets is exactly what is needed for this. The directory structure mentioned for it should work fine.

**Comment by barbosa89** [comment]
Step by step, I going to create the Panorama widget:

**Step 0: Install Panellum library**

run npm command:

`npm install pannellum`

Once the library has been installed, it is necessary to configure the compilation task in the webpack.mix.js file in the root path:

```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .copy('node_modules/font-awesome/fonts', 'public/fonts')
   .copy('node_modules/pannellum/src/css/img', 'public/css/img')
   .scripts([
		'node_modules/pannellum/build/pannellum.js',
	], 'public/js/all.js')
   .styles([
                'node_modules/pannellum/build/pannellum.css',
	], 'public/css/all.css');
```
**Step 1: Create widget with console**

Run artisan command:
`php artisan make:widget Panorama`

This command going to create two files:

First: Configuration file
/app/Widgets/Panorama.php

```
    /**
     * The configuration array. 
     * Set the image property like empty. This is the image from Panellum.
     *
     * @var array
     */
    protected $config = [
        'image' => ''
    ];

    /**
     * Treat this method as a controller action.
     * Return view() or other content to display.
     */
    public function run()
    {
        // Path to widget template
        return view('widgets.panorama', [
            'config' => $this->config,
        ]);
    }
```
Second: View file
/resources/views/widgets/panorama.blade.php

```
// Print data in template: $config['image'] 
<div id="panorama" data-image="{{ $config['image'] }}"></div>
```
Using the API data, we can obtain the image path for the Panellum library. 

**Step 3: Creating Assets**

Css: public/css/widgets/panorama/panorama.css

```
#panorama {
    width: 600px;
    height: 400px;
}
```
Javascript: public/js/widgets/panorama/panorama.js

```
# Jquery is built-in in Laravel
$(document).ready(function() {
	var panorama = document.getElementById('panorama');
        # Getting image path via API Data
	var img = panorama.dataset.image;

	pannellum.viewer('panorama', {
	    "type": "equirectangular",
	    "panorama": img,
	    "autoLoad": true
	});
});
```
**Step 4: Setup controller**

Run artisan command:
`php artisan make:controller ViewerController`

This command will create a file in /app/Http/Controllers/ViewerController.php. We going to create a method:
```
    public function panorama()
    {
    	# This can be a read data from the spreadsheet
    	$dummyData = "/images/alma.jpg";

    	# Pass the data to the viewer template: ['image' => $dummyData]
    	return view('templates.viewer', ['image' => $dummyData]);
    }
```


**Step 5: Using widget in a view**

In this case, the view will be in /resources/view/templates/viewer.blade.php

```
{{-- General layout --}}
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="content">
				<div class="col-lg-12 col-lg-offset-3">
                                         {{-- Passing data to widget --}}
					@widget('panorama', ["image" => $image])
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
@endsection
```
**Step 6: Setup route**

In file /routes/web.php

`Route::get('/panorama', 'ViewerController@panorama');`

**Step 7: Setup task to Compiling widgets assets**

```
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .copy('node_modules/font-awesome/fonts', 'public/fonts')
   .copy('node_modules/pannellum/src/css/img', 'public/css/img')
   .scripts([
		'node_modules/pannellum/build/pannellum.js',
		'public/js/widgets/panorama/panorama.js'
	], 'public/js/all.js')
   .styles([
	    'public/css/main.css',
	    'node_modules/pannellum/build/pannellum.css',
	    'public/css/widgets/panorama/panorama.css'
	], 'public/css/all.css');
```

**Step 8: Run task**

Run npm command:
`npm run dev`

**Step 7: Run server**
Run artisan command:
`php artisan serve`

You can access 127.0.0.1:3000/panorama to see the widget.

**Optional**
You can create a URL in a template. In this case, I will create a link in /resources/views/welcome.
```
<!doctype html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
          ...
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if (Auth::check())
                        <a href="{{ url('/home') }}">Home</a>
                    @else
                        <a href="{{ url('/login') }}">Login</a>
                        <a href="{{ url('/register') }}">Register</a>
                        <a href="{{ url('/panorama') }}">Viewer</a>
                        <a href="{{ url('/content') }}">Livre</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>
```
![panorama](https://user-images.githubusercontent.com/9729573/28464901-9add556c-6dec-11e7-9901-8ee6b0cf9402.png)

**Comment by barbosa89** [comment]
In c9.io is not necessary compile assets, the assets have been compiled in my local machine and next I pushed the code to repository, only Run Project...
