### ISSUE TITLE
Deploy change to a2 host server on servicejoin.com URL

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#3]
Per notes in Gitter chat:

StackSavings @stacksavings 23:22
Hi Omar, there is issue wehre server on c9 always goes down after a few hours
I think its best instead to start pushing changes onto web host
can you login here when you have a chance and set it up:
https://a2ss33.a2hosting.com:2083/
stacksav / laravel1212
it hosts stacksavings.com website but this one uses CDN currently.. I think there is another domain there:
servicejoin.com
can you see if you can configure it for now to use that domain? this is just test domain I have
let me know if any questions I can try to help, I have not logged in there in a while but just logged in now to cpanel

StackSavings @stacksavings 23:28
if any steps are complex with setup there, you can keep notes in google doc and share with me, thanks

**Comment by barbosa89** [comment]
The project was deployed:
http://servicejoin.com/
