### ISSUE TITLE
Pages other than index don't work

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#5]
I tried changing link for Services, in the spreadsheet, to:

mansion/services

Now it goes to:

http://servicejoin.com/public/mansion/services

But it gives error.

Can you look into why these links don't work?

**Comment by barbosa89** [comment]
Were implemented all pages in servicejoin.com:

[Home](http://www.servicejoin.com/public/mansion/index)
[Services](http://www.servicejoin.com/public/mansion/services)
[About Us](http://www.servicejoin.com/public/mansion/about)
[Gallery](http://www.servicejoin.com/public/mansion/gallery)
[Mail Us](http://www.servicejoin.com/public/mansion/index)

Please, help me to select the definitive content in each page, then I will create the content in the spreadsheet tabs...

**Comment by stacksavings** [comment]
@barbosa89 

I tried  creating two new tabs in

https://docs.google.com/spreadsheets/d/1Mp7XBLWUbaZwcK3hliOqzayTWKMvD_9EId0yjCu5x5M/edit#gid=372604689

But these URL's do not work.

The goal is that all user has to do is create new tab and then page will work, can you check on this and clarify the current process to create new page?

http://servicejoin.com/public/mansion/testpage1

http://servicejoin.com/public/mansion/test_page2
