### ISSUE TITLE
Implement Footer

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#6]
(see also #7)

Implement a widget that displays a footer for the area shown in this image:

![screen shot 2017-09-02 at 10 08 37 am](https://user-images.githubusercontent.com/14384619/29997539-bcf3fade-8fca-11e7-85a0-a7398c932eac.png)

this widget should be set from the common tab

**Comment by barbosa89** [comment]
The Footer Widget was implemented... [ServiceJoin.com](http://servicejoin.com/public/mansion/index)

The Footer Widget uses data from common tab in the spreadsheet...
