### ISSUE TITLE
Header tab in spreadsheet should be changed to be generic / common tab

### ISSUE THREAD

**Issue by stacksavings** [stacksavings/Laravel-Modular#7]
In https://docs.google.com/spreadsheets/d/1Mp7XBLWUbaZwcK3hliOqzayTWKMvD_9EId0yjCu5x5M/edit#gid=945952499

The idea is that instead of having a header tab, we have a tab that holds anything that is supposed to display on all the pages for this layout.

1) Instead of calling it "header", it can be changed to be called "common"

2) Any other widgets that are used for the whole layout should be on this tab as well, so the changes for the footer:

https://github.com/stacksavings/Laravel-Modular/issues/6

Should go in this tab.

**Comment by barbosa89** [comment]
Header Widget was changed to use common tab... Please, help me to check the spreadsheet...

**Comment by stacksavings** [comment]
Good job, yes this seems to be working as expected.
